[package]
name = "sharex-uploader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.0-rc.1", features= ["serde_json","json"] }
cuid = "1.2.0"
serde="1.0.136"